network:
  version: 2
  ethernets:
    ens3:
      dhcp4: false
      match:
        macaddress: '52:54:00:01:01:02'
      set-name: ens3
      gateway4: 10.0.0.1
      addresses:
        - 10.0.0.2/24
      nameservers:
        search: [oam.libvirt]
        addresses: [10.0.0.1]
    ens4:
      dhcp4: false
      match:
        macaddress: '52:54:00:01:01:03'
      set-name: ens4
      addresses:
        - 10.10.0.2/24
      nameservers:
        search: [ironic.libvirt]
        addresses: [10.10.0.1]
